apiVersion: apps/v1
kind: Deployment
metadata:
  name: invoice-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: invoice-service
  template:
    metadata:
      labels:
        app: invoice-service
    spec:
      containers:
        - name: invoice-service
          image: aswinputhukaatil/freelancex_invoice_payment_service:latest
          ports:
            - containerPort: 50056
          env:
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: invoice-service-secret
                  key: DB_HOST
            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  name: invoice-service-secret
                  key: DB_PORT
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: invoice-service-secret
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: invoice-service-secret
                  key: DB_PASSWORD
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: invoice-service-secret
                  key: DB_NAME
            - name: PORT
              valueFrom:
                secretKeyRef:
                  name: invoice-service-secret
                  key: PORT
            - name: RAZORPAY_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: invoice-service-secret
                  key: RAZORPAY_KEY_ID
            - name: RAZORPAY_KEY_SECRET
              valueFrom:
                secretKeyRef:
                  name: invoice-service-secret
                  key: RAZORPAY_KEY_SECRET
            - name: KAFKA_BROKER
              valueFrom:
                secretKeyRef:
                  name: invoice-service-secret
                  key: KAFKA_BROKER
            - name: INVOICE_KAFKA_TOPIC
              valueFrom:
                secretKeyRef:
                  name: invoice-service-secret
                  key: INVOICE_KAFKA_TOPIC
            - name: K8S_ENV
              value: "true"
