apiVersion: v1
kind: Service
metadata:
  name: freelancex_invoice_payment_service
spec:
  selector:
    app: invoice-service
  ports:
    - protocol: TCP
      port: 50056
      targetPort: 50056
  type: ClusterIP
