apiVersion: v1
kind: Service
metadata:
  name: freelancex-invoice-payment-service 
spec:
  selector:
    app: invoice-service
  ports:
    - protocol: TCP
      port: 50056
      targetPort: 50056
  type: ClusterIP
