name: CD - Deploy Invoice Payment Service to GKE

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Get GKE credentials
        uses: google-github-actions/get-gke-credentials@v2
        with:
          cluster_name: freelancex-cluster
          location: asia-south1-a
          project_id: freelancex-463106

      - name: Create/Update K8s secret for invoice-payment service
        run: |
          kubectl create secret generic invoice-service-secret \
            --from-literal=DB_HOST="${{ secrets.DB_HOST }}" \
            --from-literal=DB_PORT="${{ secrets.DB_PORT }}" \
            --from-literal=DB_USER="${{ secrets.DB_USER }}" \
            --from-literal=DB_PASSWORD="${{ secrets.DB_PASSWORD }}" \
            --from-literal=DB_NAME="${{ secrets.DB_NAME }}" \
            --from-literal=PORT="${{ secrets.PORT }}" \
            --from-literal=RAZORPAY_KEY_ID="${{ secrets.RAZORPAY_KEY_ID }}" \
            --from-literal=RAZORPAY_KEY_SECRET="${{ secrets.RAZORPAY_KEY_SECRET }}" \
            --from-literal=KAFKA_BROKER="${{ secrets.KAFKA_BROKER }}" \
            --from-literal=INVOICE_KAFKA_TOPIC="${{ secrets.INVOICE_KAFKA_TOPIC }}" \
            --dry-run=client -o yaml | kubectl apply -f -

      - name: Deploy Kubernetes resources
        run: |
          kubectl apply -f k8s/invoice-service/deployment.yaml
          kubectl apply -f k8s/invoice-service/service.yaml
