name: CD - Invoice Payment Service

on:
  push:
    paths:
      - .github/workflows/cd.yml
      - k8s/**
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: freelancex-463106

      - name: Configure Docker for GCR
        run: gcloud auth configure-docker

      - name: Set up kubectl
        run: |
          gcloud container clusters get-credentials freelancex-cluster \
            --zone asia-south1-a \
            --project freelancex-463106

      - name: Deploy to GKE
        run: |
          kubectl delete deployment invoice-service --ignore-not-found
          envsubst < k8s/deployment.yaml | kubectl apply -f -
          kubectl apply -f k8s/service.yaml
        env:
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          RAZORPAY_KEY_ID: ${{ secrets.RAZORPAY_KEY_ID }}
          RAZORPAY_KEY_SECRET: ${{ secrets.RAZORPAY_KEY_SECRET }}
